### PR TITLE
Cleanup Old Modules

### PR DESCRIPTION
**Pull request by Y2Kwastaken**
A Lot of old modules use some legacy strategies or deprecated methods within them namely the old command API. The goal of this PR is to renovate these modules and get them up to date with newer API and removing as many references to deprecated APIs as possible

This PR depends upon
- #156 
- #155

### CODE REVIEW

**Comment by mfnalex** [comment]
Is this still a draft? :p

**Comment by Y2Kwastaken** [comment]
> Is this still a draft? :p

Yes. There is a few more modules that must be done.

**Comment by mfnalex** [comment]
Alrighty <3

**Comment by Y2Kwastaken** [comment]
ready for review now

**Pull request merged**
